// @ts-nocheck
/* eslint-disable */
// Generated by tauri-specta. Do not edit.
// This file has been generated by Tauri Specta. Do not edit this file manually.

import { invoke as __TAURI_INVOKE } from "@tauri-apps/api/core";
import * as __TAURI_EVENT from "@tauri-apps/api/event";

/** Commands */
export const commands = {
	/**  M0 round-trip check. */
	ping: (message: string) => __TAURI_INVOKE<string>("ping", { message }),
	getAppInfo: () => __TAURI_INVOKE<AppInfo>("get_app_info"),
	/**  Capture and render endpoints with ASIO and VB-Cable flagged (FR-01). */
	listDevices: () => typedError<DeviceInfo[], AppError>(__TAURI_INVOKE("list_devices")),
	getConfig: () => __TAURI_INVOKE<AppConfig>("get_config").then((v) => (({...v,measuredLatencyMs:v.measuredLatencyMs==null?v.measuredLatencyMs:v.measuredLatencyMs}) as typeof v)),
	/**
	 *  Patch persisted settings (FR-20); rebuilds the engine when devices change.
	 *  A new hotkey takes effect right away; if it's invalid or taken, nothing
	 *  is saved and the old one keeps working.
	 */
	setConfig: (patch: ConfigPatch) => typedError<AppConfig, AppError>(__TAURI_INVOKE("set_config", { patch: ({...patch,monitorVolume:patch.monitorVolume==null?patch.monitorVolume:patch.monitorVolume}) })).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,measuredLatencyMs:v.data.measuredLatencyMs==null?v.data.measuredLatencyMs:v.data.measuredLatencyMs}) } : v) as typeof v)),
	/**  Open all streams through the fallback chain (FR-02). */
	startEngine: () => typedError<EngineStatusEvent, AppError>(__TAURI_INVOKE("start_engine")).then((v) => ((v.status === "ok" ? { ...v, data: ({...v.data,engine:v.data.engine==null?v.data.engine:v.data.engine}) } : v) as typeof v)),
	stopEngine: () => __TAURI_INVOKE<EngineStatusEvent>("stop_engine").then((v) => (({...v,engine:v.engine==null?v.engine:v.engine}) as typeof v)),
	getEngineStatus: () => __TAURI_INVOKE<EngineStatusEvent>("get_engine_status").then((v) => (({...v,engine:v.engine==null?v.engine:v.engine}) as typeof v)),
	/**
	 *  Live parameter change (FR-11): atomics to the audio thread, config saved
	 *  by the control loop.
	 */
	setParams: (patch: ParamsPatch) => __TAURI_INVOKE<TuningParams>("set_params", { patch: ({...patch,retuneMs:patch.retuneMs==null?patch.retuneMs:patch.retuneMs,humanize:patch.humanize==null?patch.humanize:patch.humanize,mix:patch.mix==null?patch.mix:patch.mix,gateThresholdDb:patch.gateThresholdDb==null?patch.gateThresholdDb:patch.gateThresholdDb}) }),
	setBypass: (bypass: boolean) => __TAURI_INVOKE<boolean>("set_bypass", { bypass }),
	/**  The registered tuning hotkey and any problem registering the configured one. */
	getHotkeyStatus: () => __TAURI_INVOKE<HotkeyStatus>("get_hotkey_status"),
	/**  Acoustic loopback test (FR-16). */
	runLatencyTest: () => typedError<LatencyResult, AppError>(__TAURI_INVOKE("run_latency_test")),
	/**  VB-Cable, conflicts, Discord session, sidetone and Bluetooth (FR-12, FR-13). */
	runSetupCheck: () => typedError<SetupReport, AppError>(__TAURI_INVOKE("run_setup_check")),
	/**  "Use for all apps" (FR-14). */
	setRouteAllApps: (enabled: boolean) => typedError<boolean, AppError>(__TAURI_INVOKE("set_route_all_apps", { enabled })),
	openAsioPanel: () => typedError<null, AppError>(__TAURI_INVOKE("open_asio_panel")),
	/**  Diagnostics panel (FR-18). */
	getDiagnostics: () => __TAURI_INVOKE<Diagnostics>("get_diagnostics").then((v) => (({...v,engine:v.engine==null?v.engine:v.engine,meters:v.meters==null?v.meters:v.meters,measuredLatencyMs:v.measuredLatencyMs==null?v.measuredLatencyMs:v.measuredLatencyMs}) as typeof v)),
	/**  Mark the wizard done (FR-12). */
	completeWizard: () => __TAURI_INVOKE<AppConfig>("complete_wizard").then((v) => (({...v,measuredLatencyMs:v.measuredLatencyMs==null?v.measuredLatencyMs:v.measuredLatencyMs}) as typeof v)),
	/**  Launch at login (FR-19). */
	setLaunchAtLogin: (enabled: boolean) => typedError<boolean, AppError>(__TAURI_INVOKE("set_launch_at_login", { enabled })),
	/**  Save the current parameters as a named preset (FR-21). */
	savePreset: (name: string) => typedError<Preset[], AppError>(__TAURI_INVOKE("save_preset", { name })),
	loadPreset: (name: string) => typedError<TuningParams, AppError>(__TAURI_INVOKE("load_preset", { name })),
	deletePreset: (name: string) => __TAURI_INVOKE<Preset[]>("delete_preset", { name }),
	getUpdateStatus: () => __TAURI_INVOKE<UpdateStatus>("get_update_status"),
	/**  Manual "Check for updates" (FR-22). */
	checkForUpdate: () => typedError<UpdateStatus, AppError>(__TAURI_INVOKE("check_for_update")),
	/**  Install a downloaded update and restart. */
	installUpdate: () => typedError<null, AppError>(__TAURI_INVOKE("install_update")),
	/**  Hide to tray (the engine keeps running). */
	hideWindow: () => __TAURI_INVOKE<void>("hide_window"),
	quitApp: () => __TAURI_INVOKE<void>("quit_app"),
};

/** Events */
export const events = {
	bypassEvent: makeEvent<BypassEvent>("bypass-event"),
	devicesChangedEvent: makeEvent<DevicesChangedEvent>("devices-changed-event"),
	engineStatusEvent: makeEvent<EngineStatusEvent>("engine-status-event", (v) => ({...v,engine:v.engine==null?v.engine:v.engine}), (v) => ({...v,engine:v.engine==null?v.engine:v.engine})),
	errorEvent: makeEvent<ErrorEvent>("error-event"),
	metersEvent: makeEvent<MetersEvent>("meters-event"),
	updateEvent: makeEvent<UpdateEvent>("update-event"),
};

/* Types */
/**
 *  Missing fields are filled from [`AppConfig::default`] by [`migrate`], so
 *  the type itself has no serde defaults (keeps the TS type strict).
 */
export type AppConfig = {
	schemaVersion: number,
	params: TuningParams,
	/**  Endpoint IDs; `None` = system default. */
	captureDevice: string | null,
	monitorDevice: string | null,
	monitorEnabled: boolean,
	monitorVolume: number,
	/**  Send the tuned voice into VB-Cable (the virtual mic). */
	virtualMicEnabled: boolean,
	allowExclusive: boolean,
	allowAsio: boolean,
	/**  FR-14 toggle as the user last set it. */
	routeAllApps: boolean,
	/**  Saved defaults while "Use for all apps" is active. */
	routingBackup: RoutingBackup | null,
	wizardCompleted: boolean,
	launchAtLogin: boolean,
	startEngineOnLaunch: boolean,
	bypassHotkey: string,
	autoUpdate: boolean,
	presets: Preset[],
	/**  Last acoustic loopback measurement, ms. */
	measuredLatencyMs: number | null,
};

/**  Error returned by every command. `message` is shown to the user as-is. */
export type AppError = {
	kind: ErrorKind,
	message: string,
};

export type AppInfo = {
	version: string,
	platform: string,
	/**  Show the setup wizard (first run, or launched with `--first-run`). */
	showWizard: boolean,
	asioCompiled: boolean,
};

/**  Capture fallback chain, best first (FR-02). */
export type BackendTier = "asio" | "wasapiExclusive" | "wasapiSharedLowLatency" | "wasapiShared" | "mock";

/**
 *  Bypass toggled from tray or hotkey (FR-10). `false` = tuning and
 *  monitoring on.
 */
export type BypassEvent = boolean;

/**  Partial update from the UI (`set_config`). `None` leaves a field alone. */
export type ConfigPatch = {
	captureDevice?: string | null,
	monitorDevice?: string | null,
	monitorEnabled?: boolean | null,
	monitorVolume?: number | null,
	virtualMicEnabled?: boolean | null,
	allowExclusive?: boolean | null,
	allowAsio?: boolean | null,
	startEngineOnLaunch?: boolean | null,
	bypassHotkey?: string | null,
	autoUpdate?: boolean | null,
};

/**  One capture or render endpoint (FR-01). */
export type DeviceInfo = {
	/**  Stable endpoint ID (persisted in config). */
	id: string,
	name: string,
	direction: Direction,
	isDefault: boolean,
	isDefaultCommunications: boolean,
	/**  "CABLE Input" / "CABLE Output" from VB-Audio. */
	isVbCable: boolean,
	isBluetooth: boolean,
	/**  Name of the ASIO driver that owns this device, if any. */
	asioDriver: string | null,
	/**
	 *  Physical device container; capture and render endpoints of one USB
	 *  headset share it (one clock → no resampling).
	 */
	containerId: string | null,
};

/**  Device list changed (FR-01 live updates). */
export type DevicesChangedEvent = DeviceInfo[];

export type Diagnostics = {
	appVersion: string,
	os: string,
	audioBackend: string,
	supervisor: SupervisorStatus,
	engine: EngineStatus | null,
	meters: MeterSnapshot | null,
	measuredLatencyMs: number | null,
	logDir: string,
	configPath: string,
	/**  Plain-text report for support. */
	report: string,
};

export type Direction = "capture" | "render";

/**  Meter snapshot updated by every [`Tuner::process`] call (FR-17). */
export type DspMeters = {
	/**  Peak input level in dBFS. */
	inputDb: number,
	/**  Detected pitch in Hz, 0 when unvoiced. */
	detectedHz: number,
	/**  Target MIDI note, −1 when there is none. */
	targetMidi: number,
	/**  Correction currently applied, in cents. */
	correctionCents: number,
	voiced: boolean,
	gateOpen: boolean,
};

/**  Snapshot of what the engine negotiated (FR-02 tier, FR-16 estimate). */
export type EngineStatus = {
	capture: StreamInfo,
	monitor: StreamInfo,
	cable: StreamInfo | null,
	cableError: string | null,
	monitorResampling: boolean,
	dspLatencyMs: number,
	/**  Capture period + DSP + ring + render period + stream latencies. */
	estimatedLatencyMs: number,
};

/**  Engine state, tier, latency estimate (FR-02, FR-16). */
export type EngineStatusEvent = {
	supervisor: SupervisorStatus,
	engine: EngineStatus | null,
	bypass: boolean,
};

/**  A user-facing error from a background task. */
export type ErrorEvent = string;

export type ErrorKind = "device" | "deviceInUse" | "notRunning" | "latency" | "unsupported" | "config" | "update" | "internal";

/**  What the UI shows under the hotkey setting. */
export type HotkeyStatus = {
	/**  The registered accelerator; `None` if nothing could be registered. */
	active: string | null,
	/**  Why the configured hotkey isn't the active one. */
	problem: string | null,
};

/**  A VB-Cable endpoint that exists but Windows won't let apps open. */
export type InactiveCable = {
	name: string,
	isCapture: boolean,
	/**  Turned off in Sound settings (otherwise reported unplugged). */
	disabled: boolean,
};

/**  Result of a loopback measurement. */
export type LatencyResult = {
	/**  Hardware + buffering round trip (DSP bypassed), ms. */
	hardwareMs: number,
	/**  `hardware_ms` plus the DSP's algorithmic latency, ms. */
	totalMs: number,
	/**  Normalised correlation peak, 0…1. */
	confidence: number,
};

/**  Meters and counters for the UI (FR-17, FR-18). */
export type MeterSnapshot = {
	dsp: DspMeters,
	monitorFillMs: number,
	cableFillMs: number,
	/**  Cable resampler ratio relative to nominal. */
	cableRatio: number,
	xruns: number,
	captureDiscontinuities: number,
	monitorUnderruns: number,
	cableUnderruns: number,
	ringOverflows: number,
	callbackP99Us: number,
	callbackMaxUs: number,
	/**  Duration of one capture period, the budget each callback must meet. */
	callbackBudgetUs: number,
};

/**  30 Hz meters (FR-17) while the window is visible. */
export type MetersEvent = MeterSnapshot;

/**  Partial tuning parameter update. */
export type ParamsPatch = {
	key?: number | null,
	scale?: Scale | null,
	customMask?: number | null,
	retuneMs?: number | null,
	humanize?: number | null,
	voiceRange?: VoiceRange | null,
	mix?: number | null,
	gateThresholdDb?: number | null,
	bypass?: boolean | null,
};

/**  A named tuning preset (FR-21). */
export type Preset = {
	name: string,
	params: TuningParams,
};

/**  Saved defaults, stored in the app config. */
export type RoutingBackup = {
	console: string | null,
	communications: string | null,
	/**  True while our change is in effect: "restore on next launch". */
	dirty: boolean,
};

/**  Scale used to pick target notes (FR-06). */
export type Scale = "chromatic" | "major" | "naturalMinor" | 
/**  Uses [`TuningParams::custom_mask`] (absolute pitch classes, bit 0 = C). */
"custom";

/**  Everything the wizard and the setup panel show. */
export type SetupReport = {
	vbCableInstalled: boolean,
	cableInputId: string | null,
	cableOutputId: string | null,
	/**
	 *  Why VB-Cable looks missing: its endpoints exist but are disabled or
	 *  unplugged (only for sides with no active endpoint).
	 */
	inactiveCables: InactiveCable[],
	/**  Other apps already sending audio into CABLE Input (OBS, music…). */
	cableConflicts: string[],
	/**  A Discord process has a capture session on CABLE Output. */
	discordDetected: boolean,
	/**  …and it is currently active (Discord is listening right now). */
	discordActive: boolean,
	/**  Selected mic or headphones are Bluetooth (high latency, not supported). */
	bluetoothWarning: boolean,
	/**  "Listen to this device" is on for the selected mic (doubled voice). */
	sidetoneWarning: boolean,
};

/**  What a running stream actually negotiated. */
export type StreamInfo = {
	deviceId: string,
	deviceName: string,
	tier: BackendTier,
	sampleRate: number,
	channels: number,
	/**  Device period in frames. */
	periodFrames: number,
	/**  Extra latency reported by the stream (`GetStreamLatency`), in frames. */
	streamLatencyFrames: number,
	/**  Tiers tried before this one, with the reason each failed. */
	fallbacks: TierAttempt[],
};

export type SupervisorState = "stopped" | "running" | 
/**  Wants to run but no stream could be opened yet. */
"recovering";

export type SupervisorStatus = {
	state: SupervisorState,
	lastError: string | null,
	restarts: number,
	/**  True while running on a substitute because the chosen device is gone. */
	usingFallbackDevice: boolean,
};

export type TierAttempt = {
	tier: BackendTier,
	error: string,
};

/**
 *  Complete tuning parameter set. Plain `Copy` data so it can be moved to the
 *  audio thread without allocation.
 */
export type TuningParams = {
	/**  Key root as a pitch class, 0 = C … 11 = B. */
	key: number,
	scale: Scale,
	/**  Bit `n` enables pitch class `n` (C = bit 0). Only used by [`Scale::Custom`]. */
	customMask: number,
	/**  Retune time constant, 0 (hard snap) … 200 ms (FR-07). */
	retuneMs: number,
	/**  0 … 1; preserves natural pitch movement and adds seeded detune (FR-07). */
	humanize: number,
	voiceRange: VoiceRange,
	/**  Dry/wet mix, 0 = dry … 1 = fully tuned (FR-10). */
	mix: number,
	/**  Noise gate threshold in dBFS; −100 disables the gate (FR-09). */
	gateThresholdDb: number,
	/**  Click-free bypass (FR-10). */
	bypass: boolean,
};

/**  Auto-update progress (FR-22). */
export type UpdateEvent = UpdateStatus;

export type UpdateStatus = { state: "idle" } | { state: "checking" } | { state: "upToDate"; current: string } | { state: "downloading"; version: string; percent: number | null } | { state: "ready"; version: string; notes: string | null } | { state: "error"; message: string };

/**
 *  Voice range preset (FR-08): sets the lowest tracked pitch and therefore
 *  the fixed DSP latency (≈ one period of the lowest pitch).
 */
export type VoiceRange = "low" | "mid" | "high";

/* Tauri Specta runtime */
async function typedError<T, E>(result: Promise<T>): Promise<{ status: "ok"; data: T } | { status: "error"; error: E }> {
    try {
        return { status: "ok", data: await result };
    } catch (e) {
        if (e instanceof Error) throw e;
        return { status: "error", error: e as any };
    }
}

type EventEmit<T> = [T] extends [null] ? () => Promise<void> : (payload: T) => Promise<void>;

function makeEvent<T>(name: string, serialize?: (payload: T) => unknown, deserialize?: (payload: any) => T) {
    const mapEvent = (cb: __TAURI_EVENT.EventCallback<T>) => (event: __TAURI_EVENT.Event<any>) => cb({ ...event, payload: deserialize ? deserialize(event.payload) : event.payload });
    const mapPayload = (payload: T) => serialize ? serialize(payload) : payload;

    const base = {
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => __TAURI_EVENT.once(name, mapEvent(cb)),
        emit: ((payload: T) => __TAURI_EVENT.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    };

    const fn = (target: import("@tauri-apps/api/webview").Webview | import("@tauri-apps/api/window").Window) => ({
        listen: (cb: __TAURI_EVENT.EventCallback<T>) => target.listen(name, mapEvent(cb)),
        once: (cb: __TAURI_EVENT.EventCallback<T>) => target.once(name, mapEvent(cb)),
        emit: ((payload: T) => target.emit(name, mapPayload(payload)) as unknown) as EventEmit<T>
    });

    return Object.assign(fn, base);
}

