//! Typed events (bindings generated by tauri-specta).

use serde::{Deserialize, Serialize};
use specta::Type;
use tauri_specta::Event;
use tuner_audio::DeviceInfo;
use tuner_engine::{EngineStatus, MeterSnapshot, SupervisorStatus};

use crate::updater::UpdateStatus;

/// 30 Hz meters (FR-17) while the window is visible.
#[derive(Serialize, Deserialize, Debug, Clone, Type, Event)]
pub struct MetersEvent(pub MeterSnapshot);

/// Engine state, tier, latency estimate (FR-02, FR-16).
#[derive(Serialize, Deserialize, Debug, Clone, Type, Event)]
#[serde(rename_all = "camelCase")]
pub struct EngineStatusEvent {
    pub supervisor: SupervisorStatus,
    pub engine: Option<EngineStatus>,
    pub bypass: bool,
}

/// Device list changed (FR-01 live updates).
#[derive(Serialize, Deserialize, Debug, Clone, Type, Event)]
pub struct DevicesChangedEvent(pub Vec<DeviceInfo>);

/// A user-facing error from a background task.
#[derive(Serialize, Deserialize, Debug, Clone, Type, Event)]
pub struct ErrorEvent(pub String);

/// Bypass toggled from tray or hotkey (FR-10).
#[derive(Serialize, Deserialize, Debug, Clone, Type, Event)]
pub struct BypassEvent(pub bool);

/// Auto-update progress (FR-22).
#[derive(Serialize, Deserialize, Debug, Clone, Type, Event)]
pub struct UpdateEvent(pub UpdateStatus);
