//! TunedUp desktop app (Tauri 2). Rust owns all state; the React UI is a
//! typed view over the commands and events declared here.

#![cfg_attr(test, allow(clippy::unwrap_used, clippy::expect_used))]

pub mod commands;
pub mod config;
pub mod diagnostics;
pub mod error;
pub mod events;
pub mod state;
pub mod tray;
pub mod updater;

use std::path::PathBuf;
use std::sync::atomic::Ordering;
use std::time::{Duration, Instant};

use tauri::{AppHandle, Manager, RunEvent, WindowEvent};
use tauri_plugin_global_shortcut::{GlobalShortcutExt, ShortcutState};
use tauri_specta::{collect_commands, collect_events, Builder, Event};

use crate::config::ConfigStore;
use crate::error::{AppError, AppResult, ErrorKind};
use crate::events::{DevicesChangedEvent, MetersEvent};
use crate::state::{lock, state, AppState};

/// Tauri identifier; also the `%APPDATA%` folder name.
pub const IDENTIFIER: &str = "io.github.singerbj.tunedup";
const METER_PERIOD: Duration = Duration::from_millis(33);

/// The tauri-specta builder: single source of truth for commands and events.
pub fn specta_builder() -> Builder<tauri::Wry> {
    Builder::<tauri::Wry>::new()
        .commands(collect_commands![
            commands::ping,
            commands::get_app_info,
            commands::list_devices,
            commands::get_config,
            commands::set_config,
            commands::start_engine,
            commands::stop_engine,
            commands::get_engine_status,
            commands::set_params,
            commands::set_bypass,
            commands::run_latency_test,
            commands::run_setup_check,
            commands::set_route_all_apps,
            commands::open_asio_panel,
            commands::get_diagnostics,
            commands::complete_wizard,
            commands::set_launch_at_login,
            commands::save_preset,
            commands::load_preset,
            commands::delete_preset,
            commands::get_update_status,
            commands::check_for_update,
            commands::install_update,
            commands::hide_window,
            commands::quit_app,
        ])
        .events(collect_events![
            events::MetersEvent,
            events::EngineStatusEvent,
            events::DevicesChangedEvent,
            events::ErrorEvent,
            events::BypassEvent,
            events::UpdateEvent,
        ])
}

/// Write `ui/src/bindings.ts` (debug builds and the `export_bindings` test).
pub fn export_bindings(path: &std::path::Path) -> Result<(), String> {
    specta_builder()
        // Every float we send is finite (params are sanitized, meters are
        // clamped), so plain `number` is accurate.
        .semantic_types(
            specta_typescript::semantic::Configuration::empty().enable_lossless_floats(),
        )
        .export(
            specta_typescript::Typescript::default().header(
                "// @ts-nocheck\n/* eslint-disable */\n// Generated by tauri-specta. Do not edit.",
            ),
            path,
        )
        .map_err(|e| e.to_string())
}

fn config_path() -> PathBuf {
    // %APPDATA%\<identifier>\config.json — matches Tauri's app_config_dir().
    let base = std::env::var_os("APPDATA")
        .map(PathBuf::from)
        .or_else(|| std::env::var_os("XDG_CONFIG_HOME").map(PathBuf::from))
        .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".config")))
        .unwrap_or_else(std::env::temp_dir);
    base.join(IDENTIFIER).join("config.json")
}

fn log_dir() -> PathBuf {
    let base = std::env::var_os("LOCALAPPDATA")
        .map(PathBuf::from)
        .unwrap_or_else(|| {
            config_path()
                .parent()
                .map(PathBuf::from)
                .unwrap_or_else(std::env::temp_dir)
        });
    base.join(IDENTIFIER).join("logs")
}

fn init_logging(dir: &std::path::Path) -> Option<tracing_appender::non_blocking::WorkerGuard> {
    let _ = std::fs::create_dir_all(dir);
    let appender = tracing_appender::rolling::Builder::new()
        .rotation(tracing_appender::rolling::Rotation::DAILY)
        .filename_prefix("tunedup")
        .filename_suffix("log")
        .max_log_files(7)
        .build(dir)
        .ok()?;
    let (writer, guard) = tracing_appender::non_blocking(appender);
    let _ = tracing_subscriber::fmt()
        .with_env_filter(
            tracing_subscriber::EnvFilter::try_from_default_env()
                .unwrap_or_else(|_| tracing_subscriber::EnvFilter::new("info")),
        )
        .with_writer(writer)
        .with_ansi(false)
        .try_init();
    Some(guard)
}

/// `--restore-defaults`: used by the uninstaller (and support) to put the
/// user's default microphone back without opening the UI (NFR-08).
fn restore_defaults_headless() -> i32 {
    let store = config::SharedConfig::new(ConfigStore::load(config_path()));
    let control = tuner_win::default_endpoint_control();
    let routing = tuner_win::RouteAllApps::new(control.as_ref(), &store);
    match routing.recover_after_crash() {
        Ok(_) => 0,
        Err(e) => {
            tracing::error!("restore defaults failed: {e}");
            1
        }
    }
}

pub fn emit_status(app: &AppHandle) {
    let s = state(app);
    let ev = s.status_event();
    tray::sync(app, ev.bypass);
    let _ = ev.emit(app);
}

pub fn hide_main(app: &AppHandle) {
    if let Some(w) = app.get_webview_window("main") {
        let _ = w.hide();
    }
}

/// Stop audio, restore defaults, save config. Safe to call more than once.
pub fn shutdown(app: &AppHandle) {
    let s = state(app);
    lock(&s.supervisor).stop();
    if let Err(e) = s.routing().disable() {
        tracing::warn!("restoring default devices failed: {e}");
    }
    s.config_dirty.store(true, Ordering::Release);
    s.flush_config();
}

pub fn quit(app: &AppHandle) {
    if updater::has_pending(app) {
        // Quitting with a downloaded update installs it (FR-22).
        if updater::install(app).is_ok() {
            return;
        }
    }
    app.exit(0);
}

pub fn register_hotkey(app: &AppHandle, accelerator: &str) -> AppResult<()> {
    let gs = app.global_shortcut();
    let _ = gs.unregister_all();
    if accelerator.trim().is_empty() {
        return Ok(());
    }
    gs.register(accelerator).map_err(|e| {
        AppError::new(
            ErrorKind::Config,
            format!("Could not register hotkey \"{accelerator}\": {e}"),
        )
    })
}

/// Control loop: supervisor ticks (FR-05), 30 Hz meters (FR-17), device
/// list updates (FR-01) and debounced config saves (FR-20).
fn spawn_control_loop(app: AppHandle) {
    let _ = std::thread::Builder::new()
        .name("control-loop".into())
        .spawn(move || {
            let mut last_save = Instant::now();
            loop {
                let started = Instant::now();
                let s = state(&app);
                let devices_changed = s.devices_dirty.swap(false, Ordering::AcqRel);
                let (changed, meters) = {
                    let mut sup = lock(&s.supervisor);
                    if devices_changed {
                        sup.on_device_change();
                    }
                    let changed = sup.tick();
                    (changed, sup.engine_mut().map(|e| e.meters()))
                };
                if changed {
                    emit_status(&app);
                }
                if devices_changed {
                    if let Ok(d) = s.devices() {
                        let _ = DevicesChangedEvent(d).emit(&app);
                    }
                }
                let visible = app
                    .get_webview_window("main")
                    .and_then(|w| w.is_visible().ok())
                    .unwrap_or(false);
                if let (true, Some(m)) = (visible, meters) {
                    let _ = MetersEvent(m).emit(&app);
                }
                if last_save.elapsed() > Duration::from_secs(1) {
                    s.flush_config();
                    last_save = Instant::now();
                }
                // Hidden: tick at a lower rate to keep CPU down (NFR-04).
                let period = if visible {
                    METER_PERIOD
                } else {
                    METER_PERIOD * 4
                };
                std::thread::sleep(period.saturating_sub(started.elapsed()));
            }
        });
}

/// Entry point. Returns the process exit code.
pub fn run() -> i32 {
    let args: Vec<String> = std::env::args().collect();
    let _log_guard = init_logging(&log_dir());
    if args.iter().any(|a| a == "--restore-defaults") {
        return restore_defaults_headless();
    }
    let minimized = args.iter().any(|a| a == "--minimized");
    let first_run = args.iter().any(|a| a == "--first-run");

    let builder = specta_builder();
    #[cfg(debug_assertions)]
    {
        let out = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../ui/src/bindings.ts");
        if let Err(e) = export_bindings(&out) {
            tracing::warn!("exporting bindings failed: {e}");
        }
    }

    let store = ConfigStore::load(config_path());
    let app_state = AppState::new(store, tuner_audio::default_backend(), log_dir(), first_run);

    // NFR-08: a previous crash may have left CABLE Output as the default mic.
    match app_state.routing().recover_after_crash() {
        Ok(true) => tracing::info!("restored default recording devices left by a previous session"),
        Ok(false) => {}
        Err(e) => tracing::warn!("could not restore default devices: {e}"),
    }

    let app = tauri::Builder::default()
        .plugin(tauri_plugin_single_instance::init(|app, argv, _cwd| {
            tray::show_main(app);
            if argv.iter().any(|a| a == "--first-run") {
                let _ = state(app).status_event().emit(app);
            }
        }))
        .plugin(tauri_plugin_autostart::init(
            tauri_plugin_autostart::MacosLauncher::LaunchAgent,
            Some(vec!["--minimized"]),
        ))
        .plugin(
            tauri_plugin_global_shortcut::Builder::new()
                .with_handler(|app, _shortcut, event| {
                    if event.state == ShortcutState::Pressed {
                        let s = state(app);
                        let on = !s.controls.bypass();
                        s.set_bypass(app, on);
                    }
                })
                .build(),
        )
        .plugin(tauri_plugin_updater::Builder::new().build())
        .plugin(tauri_plugin_process::init())
        .manage(app_state)
        .invoke_handler(builder.invoke_handler())
        .setup(move |app| {
            builder.mount_events(app);
            let handle = app.handle().clone();
            tray::build(&handle)?;

            let s = state(&handle);
            let cfg = s.config();
            if let Err(e) = register_hotkey(&handle, &cfg.bypass_hotkey) {
                tracing::warn!("{e}");
            }

            let dirty = s.devices_dirty.clone();
            match tuner_win::DeviceWatcher::start(move |_| dirty.store(true, Ordering::Release)) {
                Ok(w) => *lock(&s.watcher) = Some(w),
                Err(e) => tracing::warn!("device notifications unavailable: {e}"),
            }

            if cfg.wizard_completed && cfg.start_engine_on_launch {
                if let Err(e) = commands::start_engine_inner(&handle) {
                    tracing::warn!("engine did not start: {e}");
                }
            }
            spawn_control_loop(handle.clone());
            updater::spawn_background_checks(handle.clone());

            if !minimized {
                tray::show_main(&handle);
            }
            Ok(())
        })
        .on_window_event(|window, event| {
            // Close-to-tray (FR-19): the engine keeps running.
            if let WindowEvent::CloseRequested { api, .. } = event {
                api.prevent_close();
                let _ = window.hide();
            }
        })
        .build(tauri::generate_context!());

    let app = match app {
        Ok(a) => a,
        Err(e) => {
            tracing::error!("failed to start: {e}");
            return 1;
        }
    };
    app.run(|handle, event| {
        if let RunEvent::Exit = event {
            shutdown(handle);
        }
    });
    0
}

#[cfg(test)]
mod tests {
    /// Regenerates `ui/src/bindings.ts`; CI fails if the committed file differs.
    #[test]
    fn export_bindings() {
        let out = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../ui/src/bindings.ts");
        super::export_bindings(&out).unwrap();
        assert!(std::fs::read_to_string(out).unwrap().contains("ping"));
    }
}
